version: "3"
services:
  web:
    build:
      context: ../app
    ports:
      - "80:80"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - API_KEY=${API_KEY}
    container_name: web
    networks:
      - default
      - read_sign_network

  # cron:
  #   build:
  #     context: ../02_cron
  #     dockerfile: Dockerfile
  #   container_name: cron
  #   depends_on:
  #     - web
  #   ports:
  #     - "80"
  #   networks:
  #     - default
  #     - read_sign_network

networks:
   read_sign_network:
