FROM pytorch/pytorch:latest

COPY . /code 
WORKDIR /code 

RUN apt-get update && \
    apt-get -y install libpq-dev gcc && \
    apt-get install ffmpeg libsm6 libxext6  -y && \
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install torch

EXPOSE 80

CMD flask run --host=0.0.0.0
