FROM pytorch/pytorch:latest

COPY . /code 
WORKDIR /code 

RUN apt-get update
RUN apt-get -y install libpq-dev gcc
RUN apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install torch

EXPOSE 80

CMD flask run --host=0.0.0.0
